name: mobilitem2miage
description: Projet de mobilité - M2 MIAGE.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^4.3.2+2

  # Firebase
  firebase_core : ^0.5.1
  firebase_analytics : ^6.1.0
  firebase_auth : ^0.18.2
  cloud_firestore : ^0.14.2

  # Auth
  google_sign_in: ^4.5.6

  # Map & Location
  google_maps_flutter: ^0.5.33
  location: ^3.0.0
  flutter_google_places: ^0.2.6

  # Hash
  crypto: ^2.1.0
  common_utils: ^1.2.1

  # Dependency Injection
  get_it: ^1.0.3

  # Icons & Font
  font_awesome_flutter: ^8.10.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - res/assets/maps/retro.json

    - res/assets/maps/markers/Sport_b.png
    - res/assets/maps/markers/Sport_g.png
    - res/assets/maps/markers/Sport_r.png

    - res/assets/maps/markers/Culture_b.png
    - res/assets/maps/markers/Culture_g.png
    - res/assets/maps/markers/Culture_r.png

    - res/assets/maps/markers/Gastronomie_b.png
    - res/assets/maps/markers/Gastronomie_g.png
    - res/assets/maps/markers/Gastronomie_r.png